version: '2'
services:

    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass


    consumer:
        build:
            context: .
            dockerfile: consumer/Dockerfile
        links:
            - rabbit
        depends_on:
            - rabbit


    producer:
        build:
            context: .
            dockerfile: producer/Dockerfile
        links:
            - rabbit
        depends_on:
            - rabbit