version: '3.5'
services:

    rabbit-mq:
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=rabbit
            - RABBITMQ_DEFAULT_PASS=rabbit


    consumer:
        build:
            context: .
            dockerfile: consumer/Dockerfile
        environment:
            - CELERY_HOST=rabbit-mq
            - CELERY_PORT=5672
            - CELERY_USER=rabbit
            - CELERY_PASSWORD=rabbit
        volumes:
          - ./consumer/:/app/consumer/


    producer:
        build:
            context: .
            dockerfile: producer/Dockerfile
        environment:
            - CELERY_HOST=rabbit-mq
            - CELERY_PORT=5672
            - CELERY_USER=rabbit
            - CELERY_PASSWORD=rabbit
        volumes:
            - ./producer/:/app/producer/

networks:
  default:
    external:
      name: skynet
